name: Actualizar lista de IPTV

on:
  schedule:
    - cron: '* * * * *'  # Actualizar cada minuto

jobs:
  update_iptv_list:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Descargar lista de IPTV
      run: |
        mkdir -p iptv
        curl -sSLo iptv/iptv_list.m3u https://m3ukodi.com/iptv/m3ukodiplus.php

    - name: Actualizar lista de IPTV en repositorio
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: main  # O el nombre de tu rama principal
        directory: iptv
        commit_message: Actualizar lista de IPTV
