name: Actualizar lista de IPTV

on:
  schedule:
    - cron: '0 */6 * * *'  # Actualizar cada 6 horas
  push:
    branches:
      - main  # O el nombre de tu rama principal

jobs:
  update_iptv_list:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Descargar lista de IPTV
      run: |
        curl -sSLo iptv_list.m3u https://m3ukodi.com/iptv/m3ukodiplus.php

    - name: Actualizar lista de IPTV en repositorio
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: main  # O el nombre de tu rama principal
        directory: .
        commit_message: Actualizar lista de IPTV
